apiVersion: v2
name: common-test
description: Helper chart to test different use cases of the common library
version: 0.1.0
kubeVersion: ">=1.23.0-0"
keywords:
- common
home: https://github.com/manelpb/library-charts/tree/main/helper-charts/common-test
maintainers:
- name: manelpb
dependencies:
- name: common
  repository: file://../../charts/stable/common
  version: ">=5.0.0-0"
