name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'charts/**'

jobs:
  generate-readme:
    name: Auto-generate chart README
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}

    - uses: dorny/paths-filter@v4
      id: filter
      with:
        base: ${{ github.ref }}
        list-files: shell
        filters: |
          addedOrModified:
            - added|modified: 'charts/**'

    - name: Install Helm
      if: steps.filter.outputs.addedOrModified == 'true'
      uses: azure/setup-helm@v5

    - name: Install helm-docs
      if: steps.filter.outputs.addedOrModified == 'true'
      run: |
        wget -q -O /tmp/helm-docs.deb https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.deb
        sudo dpkg -i /tmp/helm-docs.deb

    - name: Run against changed charts
      if: steps.filter.outputs.addedOrModified == 'true'
      run: |
        CHARTS=()
        PATHS=(${{ steps.filter.outputs.addedOrModified_files }})
        # Get only the chart paths
        for i in "${PATHS[@]}"
        do
            IFS='/' read -r -a path_parts <<< "$i"
            CHARTS+=("${path_parts[1]}/${path_parts[2]}")
        done

        # Remove duplicates
        CHARTS=( `for i in ${CHARTS[@]}; do echo $i; done | sort -u` )

        for i in "${CHARTS[@]}"
        do
            echo "Rendering README for chart ${i}"
            IFS='/' read -r -a chart_parts <<< "$i"
            if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
              ./hack/gen-helm-docs.sh "${chart_parts[0]}" "${chart_parts[1]}"
            fi
            echo ""
        done

  release-charts:
    runs-on: ubuntu-latest
    needs:
    - generate-readme
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v5

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: charts/*
        charts_repo_url: https://manelpb.github.io/library-charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_SKIP_EXISTING: "true"
